
language: python
addons:
  code_climate:
    repo_token: 5f3a06c425eef7be4b43627d7d07a3e46c45bdc07155217825ff7c49cb6a470c
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
cache:
  directories:
    - $HOME/.wheelhouse/
env:
  global:
    - TRAVIS_CACHE=$HOME/.travis_cache/
    - TRAVIS_NODE_VERSION="6.10.2"
  matrix:
    - TOX_ENV=javascript
    - TOX_ENV=pylint
    - TOX_ENV=py34-postgres
    - TOX_ENV=py34-sqlite
    - TOX_ENV=py27-mysql
    - TOX_ENV=py27-sqlite
before_install:
  - npm install -g npm@'>=4.5.0'
  - mkdir -p $HOME/bin
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url http://095d8acfaaf71b4a0f3767e41152620ebdda1b31@mark.stridespace.com

before_script:
  - mysql -e 'drop database if exists superset; create database superset DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci' -u root
  - mysql -u root -e "CREATE USER 'mysqluser'@'localhost' IDENTIFIED BY 'mysqluserpassword';"
  - mysql -u root -e "GRANT ALL ON superset.* TO 'mysqluser'@'localhost';"
  - psql -c 'create database superset;' -U postgres
  - psql -c "CREATE USER postgresuser WITH PASSWORD 'pguserpassword';" -U postgres
  - export PATH=${PATH}:/tmp/hive/bin
install:
  - pip install --upgrade pip
  - pip install tox tox-travis
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
script: tox -e $TOX_ENV
after_script:
  - |
    if [ "${TOX_ENV}" = "javascript" ]; then
      testspace [$TOX_ENV]superset/assets/analysis.xml [$TOX_ENV/Tests]superset/assets/xunit.xml [$TOX_ENV]superset/assets/coverage/cobertura-coverage.xml;
    elif [ "${TOX_ENV}" = "pylint" ]; then
      testspace [$TOX_ENV]analysis.log{lint};
    elif [ "${TOX_ENV}" = "py34-postgres" ]; then
      testspace [$TOX_ENV]analysis.log{lint} [$TOX_ENV/Tests]nosetests.xml{tests} [$TOX_ENV]coverage.xml;
    else
      testspace [$TOX_ENV/Tests]nosetests.xml{tests};
    fi